### ISSUE TITLE
Assert failure

### ISSUE THREAD

**Issue by arnouthoebreckx** [vbehar/helm3-unittest#12]
Hi,

Would it be possible to add an assertiontype where error would be accepted.

The use case for this is that in our charts we often use the required and or fail command to indicate that something is not setup correctly. We would like to write test cases for this to check that it's always covered.

Could be something like this

```
- it: Test failure
    set:
      image.tag: latest
    asserts:
      - hasFailed:
          pattern: '[0-9]+ tag is not valid'
```

Which would check against the error message. This could be with regex support or even just fixed string.
