### ISSUE TITLE
feature: edit release information on test, and reference maps 

### ISSUE THREAD

**Issue by TheQueenIsDead** [vbehar/helm3-unittest#8]
Hi,

Currently I see it's possible to set values, but not alter other Helm metadata before running a test.
Would it be possible to adjust the templating to include the ability to adjust values such as `.Release.Namespace`?

While here, is it possible to make assertions based on the value of a map where the key contains `.`'s?
For example it would be awesome to be able to reference something like this for an Ingress
```yaml
suite: test ingress
templates:
  - ingress.yaml
tests:
  - it: should include a default nginx snippet when not set by user
    asserts:
      - equal:
          path: metadata.annotations['nginx.ingress.kubernetes.io/configuration-snippet']
          value: "example stuff and things"
```

Apologies if it's already possible to do this, any help appreciated :-)
